development:
  sessions:
    default:
      database: contwinue_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: contwinue_test
      hosts:
        - localhost:27017
      options:
        read: :primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        read: :primary
        max_retries: 5
        retry_interval: 1
        write: { w: 1 }